- set_fact:
    volumes: "{{ volumes | json_query(jsonquery) }}"
  vars:
    jsonquery: "[].{device_name: device_name, volume_type: volume_type, volume_size: volume_size, delete_on_termination: delete_on_termination}"


- name: Create new ec2 instance
  ec2:
    profile: "{{aws_profile}}"
    key_name: "{{aws_key_name}}"
    group_id: "{{aws_security_group}}"
    instance_type: "{{aws_instance_type}}"
    image: "{{aws_ami}}"
    region: "{{region}}"
    exact_count: "1"
    instance_profile_name: "{{aws_iam_instance_profile}}"
    wait: yes
    wait_timeout: 500
    volumes: "{{volumes}}"
    monitoring: no
    #vpc_subnet_id: "{{subnets[item.1.split('-')[-1] | int - 1 % subnets | length | int].aws_ec2_subnets}}"
    #vpc_subnet_id: "{{subnets[item.0 | int % subnets | length | int].aws_ec2_subnets}}"
    assign_public_ip: no
    tenancy: default
    termination_protection: yes
    instance_tags:
      App: "{{app_name}}"
      Environment: "{{environment_type}}"
      Platform: "{{platform_name}}"
      Name: "{{item.1}}"
    count_tag:
      App: "{{app_name}}"
      Environment: "{{environment_type}}"
      Platform: "{{platform_name}}"
      Name: "{{item.1}}"
  register: ec2_new_instance
  with_indexed_items: "{{server_list}}"
