- name: declare new string array server_list
  set_fact: server_list="[]"

- name: work on all servers
  set_fact:
    all_servers: true
  when: ((servers_name is not defined) or (servers_name == "") or (servers_name | default('all') == 'all')) and ((mode is not defined) or ((mode=="")) or (mode | default('normal') == 'normal'))

- name: set server_list with_sequence
  set_fact:
    server_list: "{{server_list}} + ['{{base_name}}-{{item}}']"
  #ignore_errors: yes
  with_sequence: count={{server_count}}
  when: (all_servers is defined) and (all_servers == true)

- name: work on specific servers
  set_fact:
    all_servers: false
  when: (servers_name is defined) and (servers_name != "") and (servers_name != 'all') and ((mode is not defined) or ((mode=="")) or (mode | default('normal') == 'normal'))

- name: split servers name by comma delimiter for specific servers
  set_fact:
    specific_servers_split: "{{ servers_name.split(',') }}"
  when: (all_servers is defined) and (all_servers == false) and (servers_name is defined) and (servers_name != 'all')

- name: build manual list for specific servers
  set_fact:
    server_list: "{{server_list}} + [{{item}}]"
  with_items: specific_servers_split
  when: (all_servers is defined) and (all_servers == false) and (specific_servers_split is defined)

- name: build manual list for canary servers
  set_fact:
    server_list: "{{server_list}} + ['{{base_name}}-{{item}}']"
  with_sequence: start=1 end=1
  when: (mode is defined) and (mode == "canary")

- name: print server list
  debug: msg="{{server_list}}"

#- name: set environment short sign
#  set_fact:
#     environment_short_sign: "{{environment_type[0:1]}}"